[package]
org = "dinijay"
name = "social_media"
version = "0.1.0"
distribution = "2201.13.4"

[build-options]
observabilityIncluded = true

[dependencies]
"ballerinax/mysql" = "1.14.2"
"ballerinax/java.jdbc" = "1.11.1"